### ISSUE TITLE
Can you port deband.fx to .hlsl for videoplayers?

### ISSUE THREAD

**Issue by DanillaTech** [Fubaxiusz/fubax-shaders#10]
Hello. Deband shader improves video quality, especially with 'low' bitrate, but also works good on ~1.5hours 20gb BDRip, can you port this shader for videoplayers like MPC-HC?

**Comment by Fubaxiusz** [comment]
I think somebody already ported Deband to MPC-HC, https://reshade.me/forum/shader-discussion/5116-deband-for-videoplayers
but I will look into it
