### ISSUE TITLE
Option to use the distortion for games that already produce their own Side-By-Side 3D image?

### ISSUE THREAD

**Issue by Thornskade** [Fubaxiusz/fubax-shaders#14]
Is there a way to use this shader for old VR games that already produce a 3D SBS image but the distortion doesn't work on Oculus headsets? Games such as Team Fortress 2 or Half-Life, for example.

What this means is I'd like to get the shader to distort the left and right halves of the screen individually rather than assuming that the game needs to be converted to 3D SBS first.

**Comment by Fubaxiusz** [comment]
Yes, I'm in a process of creating new VR shader that will support 3D SBS content.
When it's ready I'll upload it.
