### ISSUE TITLE
Bring back PerfectPerspective2!

### ISSUE THREAD

**Issue by chronocide-commando** [Fubaxiusz/fubax-shaders#15]
PerspectPerspective doesn't entirely replace PerfectPerspective2. For one thing, it doesn't have Asymmetrical mode. As a person who still regularly uses PerfectPerspective2, I think its removal from the repo was premature.

**Comment by Fubaxiusz** [comment]
Hello, you can set the `PANTOMORPHIC_MODE 2` to get separate projection value for top an bottom half of the screen.
