### ISSUE TITLE
Chromakey shader not working - complete transparent screenshot instead

### ISSUE THREAD

**Issue by Mistress-light** [Fubaxiusz/fubax-shaders#19]
I have an issue where I cannot make a cut-out using Chromakey. I'm using reshade version 6.0.1

For example: 

This is the cut-out I want:
<img width="1908" alt="Schermafbeelding_2024-04-19_204911" src="https://github.com/Fubaxiusz/fubax-shaders/assets/167576444/7204a4e2-7af5-4088-a321-98f63097d852">

But it turns out completely blank (transparent) when I take a screenshot:
![FORSPOKEN_2024-04-19_16-35-22](https://github.com/Fubaxiusz/fubax-shaders/assets/167576444/53e17f7a-c8c2-446f-9aab-e876432bff60)

I have 'clear alpha channel' unchecked in the settings.

Also, I do not have the option to choose 'Alpha Transparency' under keying color:
<img width="524" alt="Schermafbeelding 2024-04-19 213017" src="https://github.com/Fubaxiusz/fubax-shaders/assets/167576444/ee1bb84d-95b8-4b09-8dfc-50dfa2a357f9">

**Comment by Fubaxiusz** [comment]
Hello @Mistress-light

fixed now :D
https://github.com/Fubaxiusz/fubax-shaders/commit/e022d6c5ae69d7ad0dee9219431299caace26c50

**Comment by Mistress-light** [comment]
Thank you so much for your time and quick update! It works like a charm!
