### ISSUE TITLE
[PerfectPerspective.fx] Failed to compile

### ISSUE THREAD

**Issue by LegendNoobz** [Fubaxiusz/fubax-shaders#20]
i got an error 
![Screenshot_7](https://github.com/Fubaxiusz/fubax-shaders/assets/43951812/33b3ab9b-6fd9-40fe-a6dc-7a9d456bdeb3)

**Comment by Fubaxiusz** [comment]
Thanks for feedback. It seems you just need to update ReShade to version 6.1.1 https://reshade.me/downloads/ReShade_Setup_6.1.1.exe as it adds the this to make image less pixelated.
